name: Go Test
on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6.2.6
        ports:
          - "6379:6379"

    container:
      image: golang:1.22

    steps:
      - uses: actions/checkout@v4

      - name: Enforce go mod tidy
        run: |
          go mod tidy
          git diff --exit-code

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        env:
          REDIS_URL: redis:6379
        run: go test -v -race ./...